### ISSUE TITLE
[RFC] use git + LFS to include a pre-built mingw toolchain in the mingwpy repo

### ISSUE THREAD

**Issue by ogrisel** [mingwpy/mingwpy#13]
[git-lfs](https://git-lfs.github.com/) makes it possible to version control large files efficiently within a git repo. Now that the `mingwpy-dev` branch of `mingw-builds` seems to yield reproducible working toolchains I think we could timestamp the results of 2 such builds (one for 64 bit and one for 32 bit) and include them in the mingwpy repo to cache the results of those very expensive builds.

We could then proceeds to write automatic scripts based on those 2 toolchains to generate the Python version specific variants and use CI to test the results of those steps.

Setting up CI to continuous rebuild gcc is to costly for traditional free CI infrastructure such as Appveyor. Setting up a dedicated managed infra to CI gcc could be doable but a lot more sysadmin work (and hosting costs). I think snapshoting some intermediate builds with git-lfs could allow us to attack phase 2 in the mean time.

What do you think @carlkl @matthew-brett @rgommers @njsmith?

**Comment by techtonik** [comment]
I am not sure that adding compiled binaries into repository is a good idea. It is better to use GitHub releases for them https://help.github.com/articles/creating-releases/ because LFS is mostly for data.

**Comment by techtonik** [comment]
> Setting up CI to continuous rebuild gcc is to costly for traditional free CI infrastructure such as Appveyor. 

What was the error with AppVeyour?

**Comment by ogrisel** [comment]
No error but it takes around 15 minutes (or more I have not timed it) on a big machine 16 cores so I am pretty sure that building gcc on appveyor with a single core is going to take more than 1h and timeout.

**Comment by ogrisel** [comment]
> I am not sure that adding compiled binaries into repository is a good idea. It is better to use GitHub releases for them https://help.github.com/articles/creating-releases/ because LFS is mostly for data. 

The goal is not to distribute this archive but make it easy to checkout an rebuild the wheels and final zip archives. Then the wheels can be released on PyPI and the matching zip archives as github release suitable for end user consumption.

Technically we could use github releases to host the intermediate toolchain archive but it's likely to be misleading for our users as it's just an intermediate output of the mingw-build script, not the final mingwpy release (those are Python-version specific because of the inclusion of the specs files).

**Comment by techtonik** [comment]
I am confused. `mingw-build` produces intermediate toolchain that is then used to build toolchain that is called `mingwpy`? I'd certainly appreciate more explanation in readme with a [diagram](http://interactive.blockdiag.com/).

**Comment by ogrisel** [comment]
[mingw-builds](https://github.com/niXman/mingw-builds) is a set of scripts to build generic mingw-w64 (32 and 64 bit) toolchains (that includes gcc, binutils and mingw-w64 stuff to make them work on windows). You can pass several options to parameterize your toolchain in different ways (e.g. static linking of gcc runtime libraries). To make python extensions binary compatible with MSVC built Python interpreters, we need several options not enabled by default in the official mingw-w64 toolchains as [they are specific to our Python related use case](https://mingwpy.github.io/issues.html), some of which are currently implemented only in @carlkl's fork of the mingw-builds repo and not yet contributed upstream (although this is planned).

Anyway once you compile the two toolchains (one for 32 bit and one for 64 bit) with [our specific options enabled](https://github.com/mingwpy/mingwpy/blob/master/mingwpy_builds_readme.md), you further need to "post-configure" the toolchains with Python-version specific spec files (4 cases: 2 for 32 bit and 64 bit Python 2.6 and 2.7 and 2 for 32 bit and 64 bit Python 3.3 and 3.4). Then we need to package the resulting toolchain into 8 wheels (for each Python version and architecture combo.

**Comment by njsmith** [comment]
> "post-configure" the toolchains with Python-version specific spec files (4 cases: 2 for 32 bit and 64 bit Python 2.6 and 2.7 and 2 for 32 bit and 64 bit Python 3.3 and 3.4)

Note that it should in principle be possible to collapse the 2.6/2.7 and 3.3/3.4 spec files together and instead have the behavior chosen by a flag like `-mmsvc2008`/`-mmsvc2010`. (Then build systems of course would need to pass this flag, though, instead of just having the defaults magically work.)

> Then we need to package the resulting toolchain into 8 wheels (for each Python version and architecture combo.

Even without the refinement suggested above, I think it's just 4 wheels. You can use names like `mingwpy-py3-cp33.cp34-...` to say that a wheel works with cpython 3.3 or 3.4, only.

**Comment by carlkl** [comment]
I put this to my list of unanswered questions for the documention work. 

In principle specs files for msvcr90 and msvcr100 could be combined into one _standalone_ toolchain. This does not apply to a future VS 2015 compatible toolchain, as some basic blocks are fundamently different (i.e. file descriptors)

And to distuingish between toolchain builder and wheel builder makes sense as these could be developed more or less independently from each other. Hence the wish to have precompiled toolchains for reuse. +1 from me. My hope is, that mingw-w64 v5 is released next time, so there is no need to rely on mingw-w64 trunk anymore. Therefore the gcc-5.3.0 based toolchain should be more or less stable in foreseeable future.

There are other questions i.e. version numbering that should be discussed in a different issue.

**Comment by rgommers** [comment]
Makes sense. I looked at LFS when it was first announced (https://github.com/blog/1986-announcing-git-large-file-storage-lfs), and the bandwidth quota of 1 GB per month was an issue then. I don't see that limit mentioned in the docs anymore though, so guess that was only in the early access phase.

**Comment by ogrisel** [comment]
> Note that it should in principle be possible to collapse the 2.6/2.7 and 3.3/3.4 spec files together and instead have the behavior chosen by a flag like -mmsvc2008/-mmsvc2010. (Then build systems of course would need to pass this flag, though, instead of just having the defaults magically work.)

Yes and it we don't want to break the build on projects that use Python 2.7 distutils to build their extensions. Those projects will likely not want to change a "working" build system.

**Comment by matthew-brett** [comment]
Could we instead host the builds on rackspace, with an MD5 hash, and point
to these from the repository?​

**Comment by ogrisel** [comment]
We could but then we have to manage upload credentials. I thought that git-lfs would be operationally simpler: anybody with github push rights can upload a new version of the base toolchain.

**Comment by carlkl** [comment]
I would like to have a _standalone_ release first, say within the next two weeks. Uploading artifacts > 20 MB is not possible with the browser interface. One has to use something like https://github.com/aktau/github-release (written in go, but this doesn't matter).

My questions is: what to include in a release:? what to include in an build artifact hosted on rackspace? What comes to my mind:
- specs for all C-runtime variants: `msvcrt, msvcr90, msvcr100`
- GDB. I prefer a build _without_ python support (due to size)
- genlib (mingw-w64_trunk) very useful, but still missing in mingw-builds
- what else?

What is the prefered way to deploy releases? Deploy artifacts from local development box or from i.e. Rackspace?

**Comment by ogrisel** [comment]
> What is the prefered way to deploy releases? Deploy artifacts from local development box or from i.e. Rackspace?

That does not matter much if we do the deployment manually. What matter more is do we try to setup an hosted / automated platform to build, test and upload a release with a continuous integration system from a tag pushed to a github repo? This is more complex to setup as the free account of appveyor is not powerful enough.

> GDB. I prefer a build without python support (due to size)

Let's do without first the first release and we can change our minds later.

> genlib (mingw-w64_trunk) very useful, but still missing in mingw-builds

Why is this necessary or useful in the mingwpy context? For debugging?

**Comment by carlkl** [comment]
> Why is this necessary or useful in the mingwpy context? For debugging?

genlib is able to create import libraries in MSVC style. It is part of mingw-w64 trunk since some weeks but has to be added into the mingw-builds build system. 

So the decision is to leave it as it is for the first release and add all the nice to have's later on?

**Comment by ogrisel** [comment]
> genlib is able to create import libraries in MSVC style.

Why is it useful or necessary for the mingwpy case? To make it possible for third party developers to use MSVC to build extensions that use the C API of an extensions that was built with mingwpy?

> So the decision is to leave it as it is for the first release and add all the nice to have's later on?

+1

**Comment by carlkl** [comment]
Because you need it all ...

Let me give one example: anaconda deploys conda packages for libraries build with MSVC. Due to the binutils patch of @njsmith these libraries will be accesible for use with mingwpy without hassle. 

On the other side it will be possible in future to build and deploy library packages (conda | wheel) with mingwpy with MSVC style import libraries included. Hence these libraries packages can be used regardless if you use mingwpy or MSVC later on. Thus the genlib tool will be important in future.

gdb is not that important for inclusion in mingwpy as it can (and should?) be installed independently from mingwpy and python.

**Comment by ogrisel** [comment]
> On the other side it will be possible in future to build and deploy library packages (conda | wheel) with mingwpy with MSVC style import libraries included. Hence these libraries packages can be used regardless if you use mingwpy or MSVC later on. Thus the genlib tool will be important in future.

Alright thanks for the clarification.

> gdb is not that important for inclusion in mingwpy as it can (and should?) be installed independently from mingwpy and python.

+1

**Comment by ogrisel** [comment]
I pushed some pre-built toolchains on a rackspace container to get started:

https://8f55531b0432ac914da3-7f407ad05f03da00978ba0b8ec6c202f.ssl.cf2.rackcdn.com/i686-5.3.0-static-release-win32-sjlj-rt_v4-rev20160317.7z
https://8f55531b0432ac914da3-7f407ad05f03da00978ba0b8ec6c202f.ssl.cf2.rackcdn.com/x86_64-5.3.0-static-release-win32-seh-rt_v4-rev20160317.7z

I already gave the rackspace credentials to @carlkl and @matthew-brett by private email in the past. If you need a new build with a more recent version of the mingw-w64 libs just ping me. It takes me around 1h to start a biggish windows VM, build everything and do the upload.

Let's close this issue for now. We can always decide to move to git LFS later if people prefer.
