### ISSUE TITLE
request for comment: should mingwpy be build statically in future or not?

### ISSUE THREAD

**Issue by carlkl** [mingwpy/mingwpy#23]
please take care of the discussion on: https://github.com/conda-forge/openblas-feedstock/issues/2

@tkelman completely disagrees about the way mingwpy is build right now: https://mingwpy.github.io/mingwpy.html#customizations-over-standard-mingw-builds-releases , especially the fact, that mingwpy creates so-called _statically-linked_ binaries.

The standard way to build binaries creates dependencies on one or more GCC runtime DLLs.

For 64bit binaries this would be:
- libgcc_s_seh-1.dll
- libgfortran-3.dll
- libgomp-1.dll
- libquadmath-0.dll
- libssp-0.dll
- libstdc++-6.dll
- libwinpthread-1.dll

To get rid of these dependencies mingwpy links the code statically to the binary extension files (*.pyd). Handling these dependencies within CPython is not as trivial as it seems: https://github.com/conda-forge/openblas-feedstock/issues/2#issuecomment-215972149

As an alternative to _statically building_ a _non statically_ mingwpy could handle these dependencies as described here:

https://github.com/conda-forge/openblas-feedstock/issues/2#issuecomment-215970405:

> An obvious solution is to create a dedicated mingw-w64 runtime package as a requirement 
> to all mingw-w64 or mingwpy build extensions. This package could preload all gcc runtimes 
> with the help of ctypes into the process space. However, there wasn't an aggrement on such 
> a solution in the community.

**Comment by tkelman** [comment]
Static linking is fine for getting things initially built as you have been doing, but do you agree at least conceptually that "mingw for python" needing to be a separate rebuilt configuration vs all other mingw users is not good for interoperability and reuse long term?

At the moment static linking has been making things easier for you and I'm guessing you haven't tried building things like Qt or LLVM or COIN-OR libraries yet. I'm of the opinion that static linking, in places where you might really want it, would be better to do via a flag or a wrapper script rather than baking it into a custom default configuration of the compiler.

**Comment by carlkl** [comment]
mingwpy build with a statically configuration has the significant advantage to be fully relocatable. It is deployed as wheel archive and can be use once it's installed as-is.  No need to add it the the PATH or something else. Cython and theano users are happy this way. The point is, that all gcc and biinutil binaries has to be statically linked.

If there is an agreement to have an additional _standalone_ distribution to be installed outside of the python installation as requested it _may_ be useful to use a non-statically configuration. But then two different configurations have to be handled by the mingwpy community.

**Comment by tkelman** [comment]
Relocatability doesn't need statically linked toolchain binaries. But now you're talking about how the toolchain itself is built, rather than how the toolchain is configured to build other code. Eventually if everything gets upstreamed, mingwpy shouldn't need to be responsible for compiling its own gcc at all, just the wheel installation packaging and adding some wrappers that set a few msvc-compatibility flags around an existing standard mingw-w64 build. So the configuration when building other code is the more important part as far as compatibility and reuse are concerned.

**Comment by stonebig** [comment]
as a Python 3.4/3.5 user, I would whish:
- to have the first problem solved: "mingwpy" for Python3.4 and 3.5 homogenous environnment on windows,
- leaving  problems of hetereogenous world for when we (or other ecosystems like Julia) can afford it (current grant for mingwpy is small).

**Comment by carlkl** [comment]
@tkelman, another pont is, that mingwpy with it's special configuration is needed ASAP. Pushing all changes upstream (gcc, mingw-w64, ...) should be done later.

**Comment by carlkl** [comment]
@stonebig, we are synchronized :smile:

**Comment by tkelman** [comment]
Sure, just don't let early temporary hacks lock you into design decisions that will force you to permanently maintain your own fork of gcc.

**Comment by stonebig** [comment]
I remember I tried to used the Julia module to connect to Julia from Python 3.x. But it was not working well, then sudenly nobody was responsible anymore of this baby.

nobody forces nobody in the open source world

**Comment by carlkl** [comment]
@tkelman, mingw-w64 toolchains build by @nixman or @alexpux both contain patches and customized scripts for configure and build. This applies to the TDM and equation.com and other mingw-w64 toolchains as well. In this sense **each** mingw-w64 based toolchain is a fork of gcc.

**Comment by carlkl** [comment]
@tkelman, the problem solved with the static build of mingwpy was not relocatibility (this was more a mingw32 problem I had years ago). The static build solves the pain of choosing the correct flags to ensure statically linking with the mingw-builds toolchains I had.

**Comment by tkelman** [comment]
>  each mingw-w64 based toolchain is a fork of gcc.

when they result in incompatible ABI or build configuration, yes, and this is very confusing for users and leads to bad fragmentation when you can't use libraries built with different compiler sources together. This is a bad thing, and we should avoid making the fragmentation worse. The primary builds from mingw-builds and most linux (and cygwin) distributions' cross compilers, and msys2 (only 64 bit though) are largely abi compatible with one another. TDM and equation.com and stl etc are not, so using them to distribute libraries is discouraged.

Could you elaborate on "pain of choosing the correct flags"?

**Comment by carlkl** [comment]
mingwpy's configuration is different by design:
- 32bit: we are using `-mincoming-stack-boundary=2` to global CFLAGS. Thus all binaries continue to use 16byte alignment, but assuming incoming calls are 4byte aligned (MSVC 32 bit). Necessary to be compatible with MSVC CPython. Otherwise you will encounter segfaults with SSE code.
- we are using `-mlong-double-64` as default for both 64 and 32 bit code. This is needed for compatibility with MSVC build extensions. numpy and scipy should always agree on that setting. **This is an ABI change, but only for code that is using long doubles**
- mingw-w64 uses a very dangerous default setting for the FPU register with the use of CRT_fp10.o executing FNINIT on startup. See https://sourceforge.net/p/mingw-w64/mailman/message/33080317 This setting is inconsistent by design as newly started threads have a different setting on startup. But worse: **FINIT shouldn't be executed on startup if it is be used together with MSVC code.**.  This should be changed in mingw-w64, at least for linking DLLs.
- And we use dedicated defaults for C-runtimes compatible with the used CPython version.

With the exception of long doubles https://github.com/mingwpy/mingwpy/issues/22 there are no ABI incompatibilities to standard mingw-w64 builds. The problems noted in https://github.com/mingwpy/mingwpy/issues/22 could be solved with a patch in the mingw-w64 math code (to be proved)

**Comment by njsmith** [comment]
@tkelman: so far what we've been hearing from mingw-w64 upstream is that they aren't interested in officially supporting any version of mingw-w64 that's abi compatible with msvc earlier than 2015. So we are anticipating maintaining some kind of fork in the long term.

Fortunately most of the necessary mingwpy changes are actually very small -- the trick is figuring out what they are :-). But once you know, they're mostly just a 1 line patch here or there. E.g. the static runtime stuff is just flipping a default in a configuration file.

**Comment by tkelman** [comment]
Python 2.7 support won't be needed for all that much longer. These all really seem like flags that python extension build systems should be responsible for setting when using a msvc python and mingw for extensions. This isn't an inherent default property of the compiler, it's a property of particular python related code you want to build with it. Do you ever want it to be possible to cross compile a windows extension from linux? That'll be much easier if you're not patching up gcc, but just sending it a few flags (or even consolidate into a single new flag) so you can use existing cross compiler packages once your changes are upstreamed and picked up by various distros.

**Comment by njsmith** [comment]
@tkelman: unfortunately I think some of these flags need to be set when building the toolchain in the first place :-(. If you have a libgfortran, that's a .dll file shipped with gcc that has to be linked to some CRT -- which one was it linked to? (IIRC it might be possible to avoid this if using statically linked runtimes, but you want to avoid statically linked runtimes :-).)

2.7 will remain relevant for ~4-5 years, probably. And when we drop 2.7 we should be able to drop mingwpy entirely, since by then all interesting programs and compilers will all be using the UCRT by default. In the mean time, there arne't really any simle solutions... :-/

**Comment by stonebig** [comment]
@njsmith, 

having a full set of compilers on a wheel is a feature that only mingwpy brings. Why would you want to drop that so nice capability ? I would rather love to see also a vc wheel, a clang wheel, an intelc wheel , a pyjion wheel ...

**Comment by carlkl** [comment]
@tkelman, mingwpy is build as a pip installable python package. The customization is necessary to work around possible problems you have today  with distutils, numpy.distutils and the existing CPython versions. In short words: it should run out of the box for the user.

The question I want to discuss here is:

Do we want mingwpy to be customized as it is: (1) creating statically linked binaries or (2) creating binaries with GCC runtime dependencies? 

For variant (2) we need to create an extra package with the emphasis to preload all GCC runtimes for pratical reasons.

Linux cross compilers running on OpenSUSE or similar could be customized differently, but this topic  should be discussed in a seperate issue.

**Comment by tkelman** [comment]
People using mingwpy will all have to make 2 (or 4, for 32 vs 64 bit) sets of packages for python 2.7 and 3.x. I'm mainly concerned with the latter and whether that eventual ecosystem of binaries will interoperate more broadly with mingw users who have so far been able to happily ignore the existence of msvc. Aside from people who want to use python.org's binaries, there's not much urgency in switching to the ucrt. Is anyone aside from @carlkl even actively working on it?

Static linking and whether msvc compatibility is realized via changing the defaults in the compiler build or via a set of flags that any mingw compiler would recognize are both second order concerns to the ucrt issue. If ucrt linking worked and was widely accepted as being beneficial even for mingw users who don't care about msvc compatibility, then of course dynamically linked gcc runtimes would use the ucrt.

**Comment by carlkl** [comment]
@tkelman, please write your concerns down into a dedicated issue.

If no one wants to vote for (1) or (2) I will close this issue the next 48h.

**Comment by tkelman** [comment]
Continuing with (1) is going to cause problems with C++. It's not recommended by upstream mingw-w64, as seen whenever anyone reports issues with TDM.

**Comment by njsmith** [comment]
@carlkl: as a practical matter my suggestion would be to stick with (1) for now. Quite possibly at some point we'll want to revisit that decision, but for now it's definitely the shortest path to getting usable, and the liner we can put this off then the more experience we'll have with all the relevant issues.

**Comment by carlkl** [comment]
For now we will leave it as it is until a compelling solution for variant (2) is found.

**Comment by rgommers** [comment]
I'm very late to this discussion, but for the record here's my +1 for being pragmatic. First something that works (= 1, static linking), then after getting broader uptake within the scientific Python community revisit the advantages of (2).

@tkelman brings up some good points, and things like interoperability with other mingw builds clearly have value - but not nearly as much as having a workable compiler out of the box for the Scipy stack and Cython & co. So let's first solve the immediate issues. 

Other important consideration is scope of the current funded proposal:
- yes: mingwpy wheels & working (statically linked) toolchain
- partial: UCRT support (prototype only, no upstream support included yet)
- not in scope: interoperability with other mingw builds
