### ISSUE TITLE
request for comment: drop libquadmath from mingwpy

### ISSUE THREAD

**Issue by carlkl** [mingwpy/mingwpy#24]
as my latest working local mingwpy build (not published right now) is configured without libquadmath I want to ask for feedback:

should libquadmath support removed from mingwpy?
- libquadmath is LGPL licensed and doesn't benefit from the GPL exception clause
- I couldn't find a code reference of libquadmath really used

Comments?

**Comment by stonebig** [comment]
I found one thread speaking of it in numpy: https://mail.scipy.org/pipermail/numpy-discussion/2012-February/061080.html

For windows world / data-science usage, it may be overkill.

I would forecast that float128 number crunchers may rather be on Linux hardware and supercomputers.

**Comment by carlkl** [comment]
The properties of libquadmath are largely unknown. Reports of accuracy, performance, comparison to other multiprecision libaries remains dead loss.

My impression is, that libquadmath is largely irrelevant, but I might be wrong.

**Comment by stonebig** [comment]
I saw a thread on the Julia community also: https://github.com/JuliaLang/julia/issues/757

It looks the subject  was rather dropped end 2012 because common hardware is not optimized for that.

**Comment by njsmith** [comment]
I'm 99% sure that libquadmath provides 0 value to numpy/scipy users right now. IMO we should just do whatever option is the least burden for you, which I'm guessing is to drop it. Maybe someday there will be important software that benefits from it, and maybe then we'll have leisure to worry about figuring out how to enable it, but I think right now every minute spent thinking about libquadmath is probably a minute that could be better spent on stuff that's on the critical path :-).

**Comment by techtonik** [comment]
Yes, drop it. Quantum bits on the way. =)

**Comment by carlkl** [comment]
As everyone agrees, we drop libquadmath for now
