### ISSUE TITLE
how to use the mingwpy?

### ISSUE THREAD

**Issue by selay01** [mingwpy/mingwpy#27]
1. I have intalled mingwpy accord to https://anaconda.org/carlkl/mingwpy
   which just say:pip install -i https://pypi.anaconda.org/carlkl/simple mingwpy

should i  Compiling numpy and scipy again?and accord to:
https://mingwpy.github.io/mingwpy.html
1. when i run "import scipy; scipy.test()", it says
   Python version 2.7.12 |Anaconda 4.1.1 (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)]
   nose version 1.3.7
   .....................
   Ran 23217 tests in 358.468s
   FAILED (KNOWNFAIL=60, SKIP=1834, failures=4)
   <nose.result.TextTestResult run=23217 errors=0 failures=4>

**Comment by rgommers** [comment]
Indeed. Although only do that if you plan to do development on scipy itself. Otherwise why recompile a working scipy install? What do you want to achieve with mingwpy?

**Comment by selay01** [comment]
@rgommers  I see，and i will try .
i want to set gcc/g++ as my default c/c++ compile on my win10-x86_64 of Anaconda-64bit,and make it works when using c/c++ code in scipy and numpy and weave.inline(or say scipy.weave.inline()). 
so,mingwpy might be the best choice.

**Comment by rgommers** [comment]
okay, then you're good with just the mingwpy install, no need to recompile numpy or scipy. Anything you compile with mingwpy should be compatible with your existing Python, numpy and scipy.

**Comment by rgommers** [comment]
don't use `scipy.weave` by the way, it's deprecated. You can use the standalone `weave` package (https://github.com/scipy/weave) or Cython. Cython is recommended - weave won't see much development anymore and doesn't support Python 3.x

**Comment by selay01** [comment]
@ yeah,i've seen that scipy.weave is deprecated,and weave is not recommended,and you know this is just for testing intent.

by adding the 'distutils.cfg' file under folder \Anaconda2\Lib\distutils with 
"[build]
compiler = mingw32"
i don,t need to invoke gcc by "compiler="gcc"" everytime.and it's convenient for using cython,and i,m able to solve the 'Unable to find vcvarsall.bat' error when using cython..

By the way,i,m not able to achieve one of above by install mingwpy with msys64,it's more complicated and the msys64 gets very fat.of course,this is just for testing intent..

**Comment by selay01** [comment]
@rgommers 
yeah,i've seen that scipy.weave is deprecated,and weave is not recommended,and you know this is just for testing intent.

by adding the 'distutils.cfg' file under folder \Anaconda2\Lib\distutils with 
"[build]
compiler = mingw32"
i don,t need to invoke gcc by "compiler="gcc"" everytime.and it's convenient for using cython,and i,m able to solve the 'Unable to find vcvarsall.bat' error when using cython..

By the way,i,m not able to achieve one of above by install mingwpy with msys64,it's more complicated and the msys64 gets very fat.of course,this is just for testing intent..

**Comment by rgommers** [comment]
Okay, then you're all good and doing the right things:)
