### ISSUE TITLE
Error patching gcc in the mingwpy-dev branch of mingw-builds

### ISSUE THREAD

**Issue by ogrisel** [mingwpy/mingwpy#6]
```
-> gcc-5.3.0
---> gcc-5.3.0.tar.bz2 downloaded
---> gcc-5.3.0.tar.bz2 unpacked
--> patching...Not found level for patch gcc/gcc-5.3-mlongdouble.patch, error=2
```

**Comment by ogrisel** [comment]
Here is the command I used to trigger the build (from the readme):

```
./build --mode=gcc-5.3.0 --static-gcc --arch=x86_64 --march-x64='x86-64' --mtune-x64='generic' --buildroot=/tmp/x86_64 --rev=201601 --rt-version=trunk --threads=win32 --exceptions=seh --enable-languages=c,c++,fortran --bootstrap --no-multilib --bin-compress --jobs=16
```

**Comment by ogrisel** [comment]
I tried again today from scratch (deleted the /tmp/x86_64 folder) and did a `git reset --hard && git pull` before running the build script and got a different error:

```
-> mingw-w64-crt
--> Doesn't need to download.
--> Unpack doesn't need.
--> patching...Not found level for patch mingw-w64/fpclassify.patch, error=1
```

**Comment by ogrisel** [comment]
@carlkl let's use this github issue rather than the mailing list.

**Comment by carlkl** [comment]
Maybe it's due to the fact, that one part of the fpclassify patch was included in mingw-w64 trunk today. Let me check that.

**Comment by ogrisel** [comment]
Later in the script I also had a patching error on the new gcc patch you added yesterday.

**Comment by carlkl** [comment]
Strange, my builds from yesterday worked. Can you sen the patch logs from gcc-5.3.0 (from inside the src tree)?

**Comment by ogrisel** [comment]
Have you tried to run the builds script from scratch on an empty /tmp folder?

**Comment by carlkl** [comment]
Yes, I always rm all files from /tmp before build.

**Comment by ogrisel** [comment]
I commented out the patch from `scripts/mingw-w64-crt.sh` to be able to run the next steps and it failed at:

```
-> gcc-5.3.0
--> download gcc-5.3.0.tar.bz2... done
--> unpack gcc-5.3.0.tar.bz2... done
--> patching...Not found level for patch gcc/gcc-5.3-softfloat-no_extended.patch, error=1

```

**Comment by ogrisel** [comment]
```
Administrator@big-windows MSYS ~/mingw-builds
$ git diff
diff --git a/scripts/mingw-w64-crt.sh b/scripts/mingw-w64-crt.sh
index 93deec3..e6a16c9 100644
--- a/scripts/mingw-w64-crt.sh
+++ b/scripts/mingw-w64-crt.sh
@@ -49,7 +49,7 @@ PKG_PRIORITY=runtime
 #

 PKG_PATCHES=(
-       mingw-w64/fpclassify.patch
+#      mingw-w64/fpclassify.patch
 )

 #
```

**Comment by carlkl** [comment]
I had to change the patches to work again for the latest mingw-w64 trunk. My hope is, that mingw-w64 releases v5 in the next time. Development is to be expected much more reliable with stable releases of the underlining sources.

I tested this locally, as the rackspace remote desktop interactivity is not sufficient.

**Comment by carlkl** [comment]
I couldn't deploy a release with the binaries of the toolchain on github due its size. Therefore the binaries are deployed on bitbucket for now:

gcc-5.3.0 toolchain build with the mingwpy variant of the mingw-builds scripts. The toolchains are based on mingw-w64-trunk:

https://bitbucket.org/carlkl/mingw-w64-for-python/downloads/x86_64-5.3.0-static-release-win32-seh-rt_v4-rev201602.7z
https://bitbucket.org/carlkl/mingw-w64-for-python/downloads/i686-5.3.0-static-release-win32-sjlj-rt_v4-rev201602.7z

These builds have been depolyed to act as a input for the mingwpy wheel-builder. The configuration of the specs file missing in these builds, as this is foreseen for the wheelbuilder. All other configurations and patches are due to https://github.com/mingwpy/mingw-builds/commits/mingwpy-dev

**Comment by ogrisel** [comment]
I tried again and now the mingw-w64-crt and gcc steps build correctly but later I get a segfault at the tests step:

```
-> mingw-w64-tools-widl
--> Doesn't need to download.
--> Unpack doesn't need.
--> execute commands... done
--> configure... done
--> building... done
--> installing... done
-> make
--> download make-4.1.tar.bz2... done
--> unpack make-4.1.tar.bz2... done
--> patching... done
--> configure... done
--> building... done
--> installing... done
-> 3rdparty-post
find: ‘/tmp/x86_64/x86_64-530-win32-seh-rt_v4-rev201602-s/mingw64/opt/lib’: No such file or directory
-> cleanup
-> licenses
-> build-info
-> tests
--> g++     x86_64: "lto_int.cpp" ...             -> 0 -> done
--> g++     x86_64: "lto_test.cpp" ...            -> 0 -> done
--> g++      x86_64: "lto_test.exe" ...           -> 0 -> done
--> execute x86_64: "lto_test.exe" ...            /home/Administrator/mingw-builds/library/functions.sh: line 778:  4692 Segmentation fault      ./$_last > $_run_log 2>&1
-> 139 -> error. terminate.
```

**Comment by ogrisel** [comment]
Let's close this issue as the patching problem is solved and open a new issue for segaults in the tests.
