### ISSUE TITLE
Segfault when running lto_test.exe for x86_64 toolchain

### ISSUE THREAD

**Issue by ogrisel** [mingwpy/mingwpy#7]
I built the current state of the `mingwpy-dev` branch of [mingw-builds](https://github.com/mingwpy/mingw-builds) with:

```
./build --mode=gcc-5.3.0 --static-gcc --arch=x86_64 --march-x64='x86-64' --mtune-x64='generic' --buildroot=/tmp/x86_64 --rev=201601 --rt-version=trunk --threads=win32 --exceptions=seh --enable-languages=c,c++,fortran --bootstrap --no-multilib --bin-compress --jobs=16
```

This results in the following segfault when running the tests at the end of the script:

```
...
-> mingw-w64-tools-widl
--> Doesn't need to download.
--> Unpack doesn't need.
--> execute commands... done
--> configure... done
--> building... done
--> installing... done
-> make
--> download make-4.1.tar.bz2... done
--> unpack make-4.1.tar.bz2... done
--> patching... done
--> configure... done
--> building... done
--> installing... done
-> 3rdparty-post
find: ‘/tmp/x86_64/x86_64-530-win32-seh-rt_v4-rev201602-s/mingw64/opt/lib’: No such file or directory
-> cleanup
-> licenses
-> build-info
-> tests
--> g++     x86_64: "lto_int.cpp" ...             -> 0 -> done
--> g++     x86_64: "lto_test.cpp" ...            -> 0 -> done
--> g++      x86_64: "lto_test.exe" ...           -> 0 -> done
--> execute x86_64: "lto_test.exe" ...            /home/Administrator/mingw-builds/library/functions.sh: line 778:  4692 Segmentation fault      ./$_last > $_run_log 2>&1
-> 139 -> error. terminate.
```

**Comment by ogrisel** [comment]
In private email @carlkl said:

> I checked all my availabe mingw-w64 toolchains against the one from 2016-02.23 (depolyed on bitbucket yesterday) and all tests are consistent.
> 
> dll_test1 and dll_test2 segfault (win32). This is expected and due to the fact, that the gcc runtimes are linked statically. Nevertheless this simple test work with 64bit. This effect is usually called somthing like that: "exceptions can't be catched across dll boundaries for statically linked runtimes"
> 
> stdthread_test and sleep_test don't work. This is expected and due to the fact, that the configuration for the toolchains is to use win32 threads and not posix threads. The advantage of this configuration is, that this is usually faster. Nevertheless pthreads are allowed with the help of the winpthread library. The new C++11 threads are not available for this configuration. This may change in the future.
> 
> For now you can exclude dll_test1and dll_test to avoid the segfaults.

In my case this is the x86_64: "lto_test.exe" that fails so I think this is another issue. If this is expected we should disable the tests in the script with a comment that explains why.

**Comment by ogrisel** [comment]
Also the following line from the above log is fishy:

```
-> 3rdparty-post
find: ‘/tmp/x86_64/x86_64-530-win32-seh-rt_v4-rev201602-s/mingw64/opt/lib’: No such file or directory
```

**Comment by carlkl** [comment]
- lto_test works for me - tested with https://bitbucket.org/carlkl/mingw-w64-for-python/downloads/x86_64-5.3.0-static-release-win32-seh-rt_v4-rev201602.7z
  @ogrisel, can you put your archive of your build somewhere to download for testing?
- 3rdparty-post - it is a minor issue with the script, that pops up with an emtpy `/tmp/x86_64/x86_64-530-win32-seh-rt_v4-rev201602-s/mingw64/opt` folder. This is not critical.

**Comment by ogrisel** [comment]
Here it is:

https://www.dropbox.com/s/sv0p2m35ya8dcb1/x86_64-530-win32-seh-rt_v4-rev201602-s.7z?dl=1

Note that the Rackspace VM is still online so you can connect with a Remote Desktop client using the Administrator password and IP address I sent via private email.

**Comment by carlkl** [comment]
@ogrisel, I tested your version of the toolchain (guessing it is 2 or 3 commits mingw-w64 commits away from mine) and encountered the segfault in: `std::cout << sum << std::endl;` This needs further estimations....

**Comment by carlkl** [comment]
After some tedious tests I estimated the commit https://sourceforge.net/p/mingw-w64/mingw-w64/ci/ca451a7a45d4876065edc6755f8aab8095914b04 as the reason for this failure.
See also: https://sourceforge.net/p/mingw-w64/discussion/723797/thread/8ed60699/?limit=25#31e9/112c
As this commit is announced to be reverted, I propose to wait for this to happen and then rebuild the toolchain.

**Comment by ogrisel** [comment]
Great news, thanks for your investigation. Do we need unreleased features from mingw-w64 or could we change the build script of mingwpy to point to the tag of the latest stable release and still have a working mingwpy toolchain?

**Comment by carlkl** [comment]
One possibility is to checkout `[1bd04a]`, but important commits like
- `[801b61] (v5.0-rc1) mingw-w64-crt: Make fpclassify consistent for x86 against other archs`
- `[76119a] (HEAD, master) Fix mkstemp implementation`
- and others

are missing. If you want to make a check right now this is the way to go. To do this use the build script with `--fetch-only` and manually checkout in the mingw-w64 folder before building.

I will add a revert patch for `[ca451a] Handle __CTOR_LIST__ internally within mingw-w64` to mingw-builds if no revert commit arises in the mingw-w64 git later this day.

**Comment by ogrisel** [comment]
Alright +1 for adding a temporary patch if they do not revert today.

**Comment by carlkl** [comment]
git mingw-w64 has now reverted `[ca451a]`, so mingw-builds should build a working toolchain again.

**Comment by ogrisel** [comment]
Launching a new build from current `mingwpy-dev` after deleting `/tmp/x86_x64`. Fingers crossed.

**Comment by ogrisel** [comment]
The build succeeded! :beers: 

I will run some build tests tomorrow. Can you please push the specs files as requested in #8 so that I can manually validated phase 1?

**Comment by ogrisel** [comment]
Closing this issue now that the segfault is fixed.

**Comment by carlkl** [comment]
I sucessfully build now for 32bit and 64bit and allow myself :wine_glass:

**Comment by techtonik** [comment]
Good job. =)
