### ISSUE TITLE
Move the toolchain build instructions from mingw-builds to mingwpy's README.md

### ISSUE THREAD

**Issue by ogrisel** [mingwpy/mingwpy#9]
I think we should move the instructions from:

https://github.com/mingwpy/mingw-builds/blob/mingwpy-dev/mingwpy_readme.md

into the `README.md` of the main mingwpy repo.

This way we keep our `mingwpy-dev` branch of `mingw-builds` more inline with upstream and centralise the technical instructions to build the mingwpy toolchains in our own repo.

**Comment by techtonik** [comment]
I thought that README is the main file. Now it looks like entrypoint is different.

**Comment by ogrisel** [comment]
`README.md` is used by github to build the home page of a repo. At this point the `mingwpy-dev` branch of our clone of the `mingw-builds` has mingwpy specific instructions hidden in a file named [mingwpy_readme.md](https://github.com/mingwpy/mingw-builds/blob/mingwpy-dev/mingwpy_readme.md).

We don't want to pollute upstream `mingw-builds` with `minwpy`-specific stuff so I think it's better to gather those information in the toplevel `README.md` file of our own `mingwpy` repository.

This way the `mingwpy-dev` branch of our clone of the `mingw-builds` can be more in line with upstream `mingw-builds`. This branch can be considered as temporary container of patches that we plan to submit upstream to make the `mingw-builds` scripts generic enough for our usecase will not imposing any `mingwpy` specific documentation on them.

At the same time it will make it easier for people interested specifically in building the `mingwpy` toolchain from source to find the build instructions.

**Comment by ogrisel** [comment]
This is related to the intention to contribute to upstream `mingw-build` as tracked in #5 so as to keep the long term maintenance efforts of mingwpy to a minimum.

**Comment by techtonik** [comment]
I added entrypoint `README.md` in PR above, but I haven't got time to read and validate the info about branch layout and handling of patch queues. Need more round tuits.

**Comment by carlkl** [comment]
I moved the build instructions as requested.

**Comment by ogrisel** [comment]
Thanks!
